# Generated by Django 3.1.2 on 2021-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapk', '0002_book_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=1000, max_length=3),
        ),
    ]
