# Generated by Django 3.1.2 on 2021-08-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapk', '0003_book_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('mid_name', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
